parameters:
#    zpb_admin_phototek.example.class: ZPB\Admin\PhototekBundle\Example

services:
#    zpb_admin_phototek.example:
#        class: %zpb_admin_phototek.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
