zpb_admin_user_login:
    path: /login
    defaults: { _controller: ZPBAdminUserBundle:Login:login }
    methods: ["GET"]

zpb_admin_user_login_check:
    path: /login_check
    methods: ["GET","POST"]

zpb_admin_user_logout:
    path: /logout
    methods: ["GET"]


zpb_admin_user_enable_account:
    path: /activation
    defaults: { _controller: ZPBAdminUserBundle:Login:activation }
    methods: ["GET"]
