<?php

namespace ZPB\Admin\PhototekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoCategoryRepository extends EntityRepository
{
}
