<?php

namespace ZPB\Admin\PhototekBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends SortableRepository
{
    public function findAllByGroupedPositioned()
    {
        $categories = $this->_em->getRepository('ZPBAdminPhototekBundle:PhotoCategory')->findAll();

        if(count($categories) <1 ){
            return null;
        }

        $photos = [];

        foreach($categories as $category){
            $photos[] = ['category'=>$category, 'photos'=>$this->getBySortableGroupsQuery(['category'=>$category->getName()])->getResult()];
        }

        return $photos;

    }
}
