<?php

namespace ZPB\Admin\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostTargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTargetRepository extends EntityRepository
{
}
