parameters:
#    zpb_admin_common.example.class: ZPB\Admin\CommonBundle\Example

services:
#    zpb_admin_common.example:
#        class: %zpb_admin_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
